#############################################################################
# Makefile for building: PertModeling.app/Contents/MacOS/PertModeling
# Generated by qmake (2.01a) (Qt 4.6.0) on: Th 2 thg 12 28 00:13:29 2009
# Project:  PertModeling.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx CONFIG+=release -o Makefile PertModeling.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtXml -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		diagramscene.cpp \
		graphprovider.cpp \
		node.cpp \
		pcalculate.cpp \
		pertgraph.cpp \
		ptask.cpp \
		ptasklist.cpp \
		pxmlprovider.cpp \
		step.cpp \
		task.cpp \
		script.cpp \
		scriptstep.cpp moc_mainwindow.cpp \
		moc_diagramscene.cpp \
		qrc_resource.cpp
OBJECTS       = main.o \
		mainwindow.o \
		diagramscene.o \
		graphprovider.o \
		node.o \
		pcalculate.o \
		pertgraph.o \
		ptask.o \
		ptasklist.o \
		pxmlprovider.o \
		step.o \
		task.o \
		script.o \
		scriptstep.o \
		moc_mainwindow.o \
		moc_diagramscene.o \
		qrc_resource.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/release.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		PertModeling.pro
QMAKE_TARGET  = PertModeling
DESTDIR       = 
TARGET        = PertModeling.app/Contents/MacOS/PertModeling

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile PertModeling.app/Contents/PkgInfo PertModeling.app/Contents/Resources/empty.lproj PertModeling.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) PertModeling.app/Contents/MacOS/ || $(MKDIR) PertModeling.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PertModeling.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/release.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtXml.framework/QtXml.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx CONFIG+=release -o Makefile PertModeling.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/release.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtXml.framework/QtXml.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx CONFIG+=release -o Makefile PertModeling.pro

PertModeling.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) PertModeling.app/Contents || $(MKDIR) PertModeling.app/Contents 
	@$(DEL_FILE) PertModeling.app/Contents/PkgInfo
	@echo "APPL????" >PertModeling.app/Contents/PkgInfo
PertModeling.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) PertModeling.app/Contents/Resources || $(MKDIR) PertModeling.app/Contents/Resources 
	@touch PertModeling.app/Contents/Resources/empty.lproj
	
PertModeling.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) PertModeling.app/Contents || $(MKDIR) PertModeling.app/Contents 
	@$(DEL_FILE) PertModeling.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PertModeling,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.6/mkspecs/macx-g++/Info.plist.app >PertModeling.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/PertModeling1.0.0 || $(MKDIR) .tmp/PertModeling1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PertModeling1.0.0/ && $(COPY_FILE) --parents mainwindow.h diagramscene.h graphprovider.h node.h pcalculate.h pertgraph.h ptask.h ptasklist.h pxmlprovider.h step.h task.h script.h scriptstep.h .tmp/PertModeling1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/PertModeling1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp diagramscene.cpp graphprovider.cpp node.cpp pcalculate.cpp pertgraph.cpp ptask.cpp ptasklist.cpp pxmlprovider.cpp step.cpp task.cpp script.cpp scriptstep.cpp .tmp/PertModeling1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/PertModeling1.0.0/ && (cd `dirname .tmp/PertModeling1.0.0` && $(TAR) PertModeling1.0.0.tar PertModeling1.0.0 && $(COMPRESS) PertModeling1.0.0.tar) && $(MOVE) `dirname .tmp/PertModeling1.0.0`/PertModeling1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PertModeling1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r PertModeling.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_diagramscene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_diagramscene.cpp
moc_mainwindow.cpp: diagramscene.h \
		node.h \
		task.h \
		pertgraph.h \
		step.h \
		scriptstep.h \
		script.h \
		mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_diagramscene.cpp: node.h \
		task.h \
		diagramscene.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ diagramscene.h -o moc_diagramscene.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		icon/open.ico \
		icon/MoPert.ico \
		icon/repeat.ico \
		icon/stop.ico \
		icon/play.ico \
		icon/forward.ico \
		icon/rewind.ico
	/Developer/Tools/Qt/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Developer/Tools/Qt/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		diagramscene.h \
		node.h \
		task.h \
		pertgraph.h \
		step.h \
		scriptstep.h \
		script.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		diagramscene.h \
		node.h \
		task.h \
		pertgraph.h \
		step.h \
		scriptstep.h \
		script.h \
		ui_mainwindow.h \
		graphprovider.h \
		pcalculate.h \
		ptasklist.h \
		ptask.h \
		pxmlprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

diagramscene.o: diagramscene.cpp diagramscene.h \
		node.h \
		task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramscene.o diagramscene.cpp

graphprovider.o: graphprovider.cpp graphprovider.h \
		pertgraph.h \
		node.h \
		task.h \
		step.h \
		scriptstep.h \
		script.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphprovider.o graphprovider.cpp

node.o: node.cpp diagramscene.h \
		node.h \
		task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

pcalculate.o: pcalculate.cpp pcalculate.h \
		ptasklist.h \
		ptask.h \
		pxmlprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pcalculate.o pcalculate.cpp

pertgraph.o: pertgraph.cpp pertgraph.h \
		node.h \
		task.h \
		step.h \
		scriptstep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pertgraph.o pertgraph.cpp

ptask.o: ptask.cpp ptask.h \
		pxmlprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ptask.o ptask.cpp

ptasklist.o: ptasklist.cpp ptasklist.h \
		ptask.h \
		pxmlprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ptasklist.o ptasklist.cpp

pxmlprovider.o: pxmlprovider.cpp pxmlprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pxmlprovider.o pxmlprovider.cpp

step.o: step.cpp step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o step.o step.cpp

task.o: task.cpp task.h \
		node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o task.o task.cpp

script.o: script.cpp script.h \
		scriptstep.h \
		node.h \
		task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o script.o script.cpp

scriptstep.o: scriptstep.cpp scriptstep.h \
		node.h \
		task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scriptstep.o scriptstep.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_diagramscene.o: moc_diagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramscene.o moc_diagramscene.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

